import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Footer } from "@/components/Footer";
import { Title } from "@/components/Title";
import TopBar from "@/components/TopBar";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Is Your Train Late",
	description: "Generated by create next app",
	other: {
		"style-src-elem": "self",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div className="font-[family-name:var(--font-geist-mono)] min-h-screen flex flex-col">
					<TopBar />
					<div className="flex-1 p-20 mt-4 flex flex-col items-center">
						<Title />
						<main className="flex-1 w-full">{children}</main>
						<Footer />
					</div>
				</div>
			</body>
		</html>
	);
}
