import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Footer } from "@/components/Footer";
import { Title } from "@/components/Title";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Is Your Train Late",
	description: "Generated by create next app",
	other: {
		"style-src-elem": "self",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<div className="min-h-screen p-8 pb-20 sm:p-20 font-[family-name:var(--font-geist-mono)] flex flex-col items-center">
					<Title />
					<main className="">{children}</main>
					<Footer />
				</div>
			</body>
		</html>
	);
}
