export const majorStations = {
    AHO: "Ahonpää",
    AHV: "Ahvenus",
    AIN: "Ainola",
    ARL: "Airaksela",
    ATL: "Aittaluoto",
    AJO: "Ajos",
    APT: "Alapitkä",
    ALV: "Alavus",
    ALH: "Alholma",
    ARO: "Arola",
    ASO: "Asola",
    AVP: "Aviapolis",
    BSL: "Buslovskaja",
    DRA: "Dragsvik",
    DMV: "Dynamiittivaihde",
    EPZ: "Eläinpuisto-Zoo",
    ENO: "Eno",
    ERV: "Ervelä",
    ELA: "Eskola",
    EPO: "Espoo",
    HPJ: "Haapajärvi",
    HPS: "Haapakoski",
    HPK: "Haapamäki",
    HPA: "Haaparanta pohjoinen",
    HAA: "Haarajoki",
    HLT: "Hakosilta",
    HSI: "Haksi",
    HMA: "Hamina",
    HSL: "Hammaslahti",
    HNA: "Hanala",
    HGS: "Hangonsaari",
    HNH: "Hanhikoski",
    HKS: "Hankasalmi",
    HNK: "Hanko asema",
    HNKT: "Hanko tavara",
    HKP: "Hanko-Pohjoinen",
    HVA: "Harjavalta",
    HJ: "Harju",
    HRV: "Harviala",
    HD: "Haukipudas",
    HAU: "Haukivuori",
    HAS: "Hausjärvi tavara",
    HVS: "Haviseva",
    HVK: "Havukoski",
    HEK: "Heikkilä",
    HA: "Heinola",
    HNO: "Heinoo",
    HÄV: "Heinävaara",
    HNV: "Heinävesi",
    HKI: "Helsinki asema",
    KHK: "Helsinki Kivihaka",
    LOP: "Helsinki Louhenpuisto",
    VRJ: "Helsinki Veräjälaakso",
    HNN: "Henna",
    HR: "Herrala",
    HKH: "Hiekkaharju",
    HIR: "Hiirola",
    HK: "Hikiä",
    HLS: "Hillosensalmi",
    HH: "Hinthaara",
    HVN: "Hirvineva",
    HP: "Humppila",
    HPL: "Huopalahti",
    HKO: "Huutokoski",
    HYR: "Hyrkäs",
    HYS: "Hyrynsalmi",
    HY: "Hyvinkää asema",
    PVL: "Hyvinkää Paavola",
    HYT: "Hyvinkää tavara",
    HL: "Hämeenlinna",
    HM: "Härmä",
    HÖL: "Höljäkkä",
    II: "Ii",
    ITR: "Iisalmen teollisuusraiteet",
    ILM: "Iisalmi",
    R983: "Iisalmi (R983)",
    ITA: "Iittala",
    ILA: "Ilmala asema",
    ILR: "Ilmala ratapiha",
    IOA: "Ilola",
    ILO: "Ilomantsi",
    IMR: "Imatra asema",
    IMT: "Imatra tavara",
    IMK: "Imatrankoski",
    IMKR: "Imatrankoski-raja",
    IM: "Immola",
    IN: "Inha",
    IKR: "Inkeroinen",
    IKO: "Inkoo",
    IKY: "Isokyrö",
    JAL: "Jalasjärvi",
    JPA: "Jepua",
    JNS: "Joensuu asema",
    KPP: "Joensuu Koppola",
    PLT: "Joensuu Peltola",
    SUL: "Joensuu Sulkulahti",
    JK: "Jokela",
    JOR: "Joroinen",
    JRS: "Jorvas",
    JTS: "Joutseno",
    JKI: "Juankoski",
    JUT: "Jutila",
    JJ: "Juupajoki",
    JRI: "Juurikorpi",
    JY: "Jyväskylä",
    JÄS: "Jämsä",
    JSK: "Jämsänkoski",
    JR: "Järvelä",
    JP: "Järvenpää asema",
    KPA: "Kaipiainen",
    KLA: "Kaipola",
    KJR: "Kaitjärvi",
    KAJ: "Kajaani",
    KTN: "Kaleton",
    KAU: "Kalkku",
    KAO: "Kalliovarasto",
    KSA: "Kalvitsa",
    KGS: "Kangas",
    KAN: "Kannelmäki",
    KSI: "Kannonkoski",
    KNS: "Kannus",
    KRR: "Karhejärvi",
    KHG: "Karhukangas",
    KR: "Karjaa",
    KRU: "Karkku",
    KAR: "Karviainen",
    KSK: "Kaskinen",
    KTH: "Kattilaharju",
    KJI: "Kauhajoki",
    KHA: "Kauhava",
    KLH: "Kauklahti asema",
    KLR: "Kaulinranta",
    KNI: "Kauniainen",
    KPL: "Kauppilanmäki",
    KA: "Kausala",
    KTP: "Keitelepohja",
    KEK: "Kekomäki",
    KEO: "Kello",
    KEM: "Kemi asema",
    LI: "Kemi Lautiosaari",
    SHS: "Kemi Sahansaari",
    KJÄ: "Kemijärvi",
    KML: "Kempele",
    KEA: "Kera",
    R660: "Kerava (R660)",
    KE: "Kerava asema",
    KIÄ: "Kerimäki",
    KTI: "Kesälahti",
    KEU: "Keuruu",
    KIA: "Kiiala",
    KIL: "Kilo",
    KUA: "Kilpua",
    KNH: "Kinahmi",
    KII: "Kinni",
    KIJ: "Kirjola",
    KKN: "Kirkkonummi",
    KRN: "Kirkniemi",
    KIT: "Kitee",
    KN: "Kiukainen",
    KRV: "Kiuruvesi",
    KVJ: "Kivesjärvi",
    KIV: "Kivijärvi",
    KTÖ: "Kivistö",
    KOH: "Kohtavaara",
    KVU: "Koivu",
    KVH: "Koivuhovi",
    KVY: "Koivukylä",
    KKI: "Kokemäki",
    KOK: "Kokkola",
    KLI: "Kolari",
    KLO: "Kolho",
    KPI: "Kolppi",
    KMM: "Kommila",
    KOM: "Komu",
    KHI: "Kontiolahti",
    KON: "Kontiomäki",
    R934: "Kontiomäki (R934)",
    KRA: "Koria",
    KAS: "Korkeakoski",
    KRS: "Korso",
    KSU: "Korvensuo",
    KOS: "Koskenkorva",
    KTA: "Kotka asema",
    HOS: "Kotka Hovinsaari",
    MSS: "Kotka Mussalo",
    KTT: "Kotka tavara",
    KTS: "Kotkan satama",
    KOO: "Kotolahti",
    KV: "Kouvola asema",
    KVLA: "Kouvola lajittelu",
    OIK: "Kouvola Oikoraide",
    KVT: "Kouvola tavara",
    KOI: "Kovjoki",
    KPY: "Kruunupyy",
    KIS: "Kuivasjärvi",
    KUV: "Kullasvaara",
    KUO: "Kuopio asema",
    ILH: "Kuopio Iloharju",
    KUOT: "Kuopio tavara",
    KUT: "Kupittaa",
    KRM: "Kurkimäki",
    KU: "Kuurila",
    KUK: "Kuusankoski",
    KSN: "Kuusikkoniemi",
    KYN: "Kylänlahti",
    KY: "Kymi",
    KLN: "Kyminlinna",
    KÖ: "Kyrö",
    KYT: "Kytömaa",
    KLV: "Kälviä",
    KÄP: "Käpylä",
    KÖK: "Köykkäri",
    LAV: "Laajavuori",
    LPR: "Lahdenperä",
    LHN: "Lahnaslampi",
    LH: "Lahti",
    LAI: "Laihia",
    LAK: "Lakiala",
    LMK: "Lamminkoski",
    LAM: "Lamminniemi",
    LPJ: "Lapinjärvi",
    LNA: "Lapinlahti",
    LR: "Lappeenranta",
    LAA: "Lappila",
    LPO: "Lappohja",
    LPA: "Lapua",
    LYÖ: "Larvakytö",
    LAU: "Laukaa",
    LLA: "Laurila",
    LRS: "Lauritsala",
    LNÄ: "Leinelä",
    LKL: "Lelkola",
    LPÄ: "Lempäälä",
    LEN: "Lentoasema",
    LK: "Leppäkoski",
    LPV: "Leppävaara",
    LTS: "Leteensuo",
    LIS: "Lieksa",
    LTK: "Lieksan teollisuuskylä",
    LLH: "Lielahti",
    LVT: "Lievestuore",
    LKA: "Liminka",
    LMP: "Liminpuro",
    LUO: "Lohiluoma",
    LO: "Lohja",
    LM: "Loimaa",
    LOH: "Louhela",
    LOL: "Loukolampi",
    LVS: "Loviisan satama",
    LUI: "Luikonlahti",
    LUS: "Lusto",
    LÄ: "Luumäki",
    LHS: "Lähessuo",
    LÄP: "Länkipohja",
    MLK: "Maanselkä",
    MRI: "Maaria",
    MD: "Madesjärvi",
    MJJ: "Majajärvi",
    MKN: "Maksniemi",
    ML: "Malmi",
    MLO: "Malminkartano",
    MKA: "Mankala",
    MRK: "Markkala",
    MRL: "Martinlaakso",
    MAS: "Masala",
    MTV: "Matkaneva",
    MAT: "Mattila",
    MLL: "Melalahti",
    MSÄ: "Metsäkansa",
    MI: "Mikkeli",
    MIS: "Misi",
    MLA: "Mommila",
    MVA: "Moskova_(Leningradski)",
    MH: "Muhos",
    MUK: "Mukkula",
    MUR: "Murtomäki",
    R562: "Murtomäki (R562)",
    MSO: "Mustio",
    MST: "Mustolan satama",
    MKO: "Muukko",
    MUU: "Muurame",
    MUL: "Muurola",
    MYS: "Myllykangas",
    MKI: "Myllykoski",
    MY: "Myllymäki",
    MYL: "Myllyoja",
    MYT: "Mynttilä",
    MYN: "Mynämäki",
    MYR: "Myyrmäki",
    MÄK: "Mäkkylä",
    MLÄ: "Mäntsälä",
    MÄN: "Mänttä",
    MR: "Mäntyharju",
    MN: "Mäntyluoto",
    MN_V: "Mäntyluoto erkanemisvaihde",
    NNL: "Naantali",
    NRI: "Naarajärvi",
    NAL: "Nakkila",
    NSL: "Nastola",
    NMP: "Niemenpää",
    NII: "Niinimaa",
    NMÄ: "Niinimäki",
    NNS: "Niinisalo",
    NRL: "Niirala",
    NRLR: "Niirala-raja",
    NTH: "Niittylahti",
    NLÄ: "Nikkilä",
    NSK: "Niska",
    NVL: "Nivala",
    NOA: "Nokia",
    NM: "Nummela",
    NUA: "Nuojua",
    NRM: "Nurmes",
    NÄR: "Närpiö",
    OHM: "Ohenmäki",
    OI: "Oitti",
    OLLI: "Olli",
    ONT: "Onttola",
    OM: "Orimattila",
    OV: "Orivesi",
    OVK: "Orivesi keskusta",
    OTM: "Otanmäki",
    OT: "Otava",
    OU: "Oulainen",
    OL: "Oulu asema",
    NOK: "Oulu Nokela",
    ORI: "Oulu Oritkari",
    OLT: "Oulu tavara",
    TUA: "Oulu Tuira",
    OLK: "Oulunkylä",
    OLL: "Oulunlahti",
    PTI: "Paimenportti",
    PO: "Paimio",
    PLP: "Palopuro",
    PTO: "Paltamo",
    PAS: "Pankakoski",
    PAR: "Parikkala",
    PKO: "Parkano",
    PRL: "Parola",
    PSL: "Pasila asema",
    PAU: "Pasila autojuna-asema",
    PSLT: "Pasila tavara",
    PTG: "Patokangas",
    PA: "Pelkola",
    PEL: "Pello",
    PMI: "Peltosalmi",
    PSJ: "Peräseinäjoki",
    PSK: "Pesiökylä",
    PRK: "Petroskoi / Petrozavodsk",
    PVI: "Petäjävesi",
    PM: "Pieksämäki asema",
    PMLA: "Pieksämäki lajittelu",
    PMT: "Pieksämäki tavara",
    TMU: "Pieksämäki Temu",
    PTR: "Pietari_(Finljandski)",
    PTL: "Pietari_(Ladozhski)",
    PTS: "Pietarsaari",
    PH: "Pihlajavesi",
    PP: "Pihtipudas",
    PIK: "Piikkiö",
    PKL: "Pikkarala",
    PIO: "Pitkäkallio",
    PTK: "Pitkämäki",
    PJM: "Pitäjänmäki",
    PKU: "Pohjankuru",
    POH: "Pohjois-Haaga",
    PLU: "Pohjois-Louko",
    PKK: "Poikkeus",
    POI: "Poiksilta",
    PRI: "Pori",
    PRV: "Porvoo",
    PUS: "Puhos",
    PLA: "Puistola",
    PMK: "Pukinmäki",
    PL: "Pulsa",
    PUN: "Punkaharju",
    PUR: "Purola",
    PYK: "Pyhäkumpu",
    PYE: "Pyhäkumpu erkanemisvaihde",
    PHÄ: "Pyhäsalmi",
    PNÄ: "Pännäinen",
    R855: "Pännäinen (R855)",
    PKY: "Pääskylahti",
    RHE: "Raahe",
    RPO: "Raippo",
    RAI: "Raisio",
    RM: "Rajamäki",
    RJP: "Rajaperkiö",
    RMI: "Rantasalmi",
    RAS: "Rasinsuo",
    RLÄ: "Ratikylä",
    RAH: "Rauha",
    RHL: "Rauhalahti",
    RMA: "Rauma",
    RIO: "Raunio",
    RAT: "Rautaruukki",
    RJÄ: "Rautjärvi",
    RPH: "Rautpohja",
    RKL: "Rekola",
    REE: "Retretti",
    R060: "Riihimäki (R060)",
    R702: "Riihimäki (R702)",
    ARP: "Riihimäki Arolampi",
    RI: "Riihimäki asema",
    RILA: "Riihimäki lajittelu",
    RIT: "Riihimäki tavara",
    RJR: "Riijärvi",
    RPA: "Riippa",
    RST: "Ristiina",
    RJV: "Ristijärvi",
    ROI: "Rovaniemi",
    RHA: "Ruha",
    RNN: "Runni",
    RSU: "Ruokosuo",
    RKI: "Ruukki",
    RSM: "Ruusumäki",
    RY: "Ryttylä",
    RÖY: "Röyttä",
    SAA: "Saakoski",
    SR: "Saari",
    SRJ: "Saarijärvi",
    SLN: "Salminen",
    SLO: "Salo",
    SAM: "Sammalisto",
    STA: "Santala",
    SAU: "Saunakallio",
    SMÄ: "Saunamäki",
    SAV: "Savio",
    SL: "Savonlinna asema",
    SK: "Seinäjoki asema",
    RLA: "Seinäjoki Rahkola",
    SKT: "Seinäjoki tavara",
    SPÄ: "Selänpää",
    SPJ: "Sieppijärvi",
    SVI: "Sievi",
    SKÄ: "Siikamäki",
    R662: "Siilinjärvi (R662)",
    SIJ: "Siilinjärvi asema",
    SIM: "Simo",
    SPL: "Simpele",
    SIP: "Sipilä",
    STÖ: "Sisättö",
    STI: "Siuntio",
    SIU: "Siuro",
    SGY: "Skogby",
    SLD: "Sköldvik",
    SOA: "Soinlahti",
    SOR: "Sorsasalo",
    SKV: "Sukeva",
    SUO: "Suolahti",
    SNJ: "Suonenjoki",
    SNM: "Suoniemi",
    STG: "Svetogorsk",
    SYR: "Syrjä",
    SKI: "Syrjämäki",
    SMJ: "Sysmäjärvi",
    SÄ: "Säkäniemi",
    SKM: "Sänkimäki",
    SJ: "Sääksjärvi",
    TA: "Taavetti",
    TKO: "Tahkoluoto",
    TE: "Taipale",
    TV: "Talviainen",
    TLV: "Talvivaara",
    TMS: "Tammisaari",
    TPE: "Tampere asema",
    JVS: "Tampere Järvensivu",
    TPET: "Tampere tavara",
    VKA: "Tampere Viinikka",
    TNA: "Tapanila",
    TAP: "Tapavainola",
    TSL: "Tavastila",
    TK: "Tervajoki",
    TRV: "Tervola",
    TSO: "Tesoma",
    TUV: "Teuva",
    TKK: "Tikkala",
    TKP: "Tikkaperä",
    TKL: "Tikkurila asema",
    TOH: "Tohmajärvi",
    TL: "Toijala",
    TOI: "Toivala",
    TOL: "Tolsa",
    TOM: "Tommola",
    TRK: "Torkkeli",
    TOR: "Tornio",
    R742: "Tornio (R742)",
    TRI: "Tornio-Itäinen",
    TRR: "Tornio-raja",
    TRL: "Tuomarila",
    TJA: "Tuomioja",
    R530: "Tuomioja (R530)",
    TU: "Turenki",
    TKU: "Turku asema",
    TUS: "Turku satama",
    TKUT: "Turku tavara",
    TPV: "Tuupovaara",
    TUU: "Tuuri",
    TVE: "Tver",
    TÖR: "Törmä",
    TRÄ: "Törölä",
    UIM: "Uimaharju",
    UR: "Urjala",
    UTJ: "Utajärvi",
    UTI: "Utti",
    UKP: "Uusikaupunki",
    UKÄ: "Uusikylä",
    VKO: "Vaajakoski",
    VAA: "Vaala",
    VRA: "Vaarala",
    VS: "Vaasa",
    VJR: "Vahojärvi",
    VNA: "Vainikkala asema",
    VNAT: "Vainikkala tavara",
    VNAR: "Vainikkala-raja",
    VMO: "Valimo",
    VI: "Valkeakoski",
    VSO: "Valkeasuo",
    VLM: "Valtimo",
    VMA: "Vammala",
    VTR: "Vanattara",
    VKS: "Vantaankoski",
    VAR: "Varkaus",
    VUS: "Vartius",
    VUR: "Vartius-raja",
    VKH: "Vasikkahaka",
    VSK: "Vaskiluoto",
    VEH: "Vehkala",
    VKI: "Venetmäki",
    VN: "Vesanka",
    VK: "Viekki",
    VRM: "Vierumäki",
    VTI: "Vihanti",
    VIH: "Vihtari",
    VRI: "Vihtavuori",
    VIA: "Viiala",
    VNJ: "Viinijärvi",
    VYB: "Viipuri",
    VLH: "Villähde",
    VLP: "Vilppula",
    VIN: "Vinnilä",
    VMS: "Virkamies",
    VT: "Voltti",
    VHJ: "Vuohijärvi",
    VJO: "Vuojoki",
    VKT: "Vuokatti",
    VSL: "Vuonislahti",
    VNS: "Vuonos",
    VSA: "Vuosaari",
    VRS: "Värtsilä",
    YKST: "Ykspihlaja tavara",
    YKSV: "Ykspihlaja väliratapiha",
    YST: "Ylistaro",
    YTR: "Ylitornio",
    YLV: "Ylivalli",
    YV: "Ylivieska",
    YLK: "Yläkoski",
    YLY: "Ylämylly",
    YLÖ: "Ylöjärvi",
    YPY: "Ypykkävaara",
    ÄS: "Äetsä",
    ÄHT: "Ähtäri",
    ÄKI: "Äänekoski",
} as const;

export type StationCode = keyof typeof majorStations;

export const passengerStationCodes: ReadonlySet<string> = new Set([
    "AIN",
    "ALV",
    "AVP",
    "DRA",
    "EPZ",
    "ENO",
    "EPO",
    "HPJ",
    "HPK",
    "HPA",
    "HAA",
    "HSI",
    "HKS",
    "HNK",
    "HKP",
    "HVA",
    "HNV",
    "HKI",
    "HNN",
    "HR",
    "HKH",
    "HK",
    "HLS",
    "HH",
    "HP",
    "HPL",
    "HY",
    "HL",
    "HM",
    "HÖL",
    "ILM",
    "ITA",
    "ILA",
    "IMR",
    "IKR",
    "IKO",
    "IKY",
    "JNS",
    "JK",
    "JRS",
    "JTS",
    "JJ",
    "JY",
    "JÄS",
    "JR",
    "JP",
    "KAJ",
    "KAN",
    "KNS",
    "KR",
    "KRU",
    "KHA",
    "KLH",
    "KNI",
    "KA",
    "KEM",
    "KJÄ",
    "KML",
    "KEA",
    "KE",
    "KIÄ",
    "KTI",
    "KEU",
    "KIA",
    "KIL",
    "KKN",
    "KIT",
    "KRV",
    "KTÖ",
    "KOH",
    "KVH",
    "KVY",
    "KKI",
    "KOK",
    "KLI",
    "KLO",
    "KON",
    "KRA",
    "KRS",
    "KTA",
    "KTS",
    "KV",
    "KUO",
    "KUT",
    "KYN",
    "KY",
    "KLN",
    "KÄP",
    "LH",
    "LAI",
    "LNA",
    "LR",
    "LAA",
    "LPO",
    "LPA",
    "LNÄ",
    "LPÄ",
    "LEN",
    "LPV",
    "LIS",
    "LVT",
    "LM",
    "LOH",
    "LUS",
    "ML",
    "MLO",
    "MRL",
    "MAS",
    "MI",
    "MIS",
    "MLA",
    "MVA",
    "MH",
    "MUL",
    "MKI",
    "MY",
    "MYR",
    "MÄK",
    "MLÄ",
    "MR",
    "NSL",
    "NLÄ",
    "NVL",
    "NOA",
    "NRM",
    "OI",
    "OV",
    "OVK",
    "OU",
    "OL",
    "OLK",
    "PTI",
    "PTO",
    "PAR",
    "PKO",
    "PRL",
    "PSL",
    "PAU",
    "PEL",
    "PVI",
    "PM",
    "PTR",
    "PTL",
    "PH",
    "PJM",
    "POH",
    "PRI",
    "PRV",
    "PLA",
    "PMK",
    "PUN",
    "PUR",
    "PHÄ",
    "PNÄ",
    "PKY",
    "RKL",
    "REE",
    "RI",
    "ROI",
    "RNN",
    "RKI",
    "RY",
    "SLO",
    "STA",
    "SAU",
    "SAV",
    "SL",
    "SK",
    "SIJ",
    "SPL",
    "STI",
    "SGY",
    "SKV",
    "SNJ",
    "TMS",
    "TPE",
    "TNA",
    "TSL",
    "TK",
    "TRV",
    "TSO",
    "TKL",
    "TL",
    "TOL",
    "TOR",
    "TRI",
    "TRL",
    "TU",
    "TKU",
    "TUS",
    "TUU",
    "TVE",
    "UIM",
    "UTJ",
    "UKÄ",
    "VAA",
    "VS",
    "VNA",
    "VMO",
    "VMA",
    "VKS",
    "VAR",
    "VEH",
    "VTI",
    "VIH",
    "VIA",
    "VNJ",
    "VYB",
    "VLH",
    "VLP",
    "VSL",
    "YST",
    "YTR",
    "YV",
    "ÄHT",
]);

export const isValidStationCode = (code: string): code is StationCode => {
    return code in majorStations;
};
