import type { Train } from "@/types/trainQueryTypes";

export const defaultTrainData: Train[] = [
	{
		cancelled: false,
		commuterLineid: "",
		departureDate: "2024-11-26",
		runningCurrently: true,
		trainNumber: 267,
		timetableType: "REGULAR",
		trainType: { name: "PYO", trainCategory: { name: "Long-distance" } },
		trainLocations: [{ speed: 88, location: [25.399626, 66.413215] }],
		trainTrackingMessages: [
			{
				timestamp: "2024-11-26T19:09:00.000Z",
				trackSectionCode: "008a",
				nextTrackSectionCode: null,
				previousTrackSectionCode: null,
				type: "OCCUPY",
				station: {
					passengerTraffic: true,
					countryCode: "FI",
					location: [24.941249, 60.172097],
					name: "Helsinki asema",
					shortCode: "HKI",
					uicCode: 1,
					type: "STATION",
				},
				nextStation: {
					passengerTraffic: true,
					countryCode: "FI",
					location: [24.933521, 60.198689],
					name: "Pasila asema",
					shortCode: "PSL",
					uicCode: 10,
					type: "STATION",
				},
				previousStation: null,
			},
		],
		timeTableRows: [
			{
				type: "DEPARTURE",
				trainStopping: true,
				commercialStop: true,
				commercialTrack: "8",
				cancelled: false,
				scheduledTime: "2024-11-26T19:14:00.000Z",
				actualTime: "2024-11-26T19:16:25.000Z",
				differenceInMinutes: 2,
				liveEstimateTime: null,
				estimateSourceType: null,
				unknownDelay: null,
				station: {
					passengerTraffic: true,
					countryCode: "FI",
					location: [24.941249, 60.172097],
					name: "Helsinki asema",
					shortCode: "HKI",
					uicCode: 1,
					type: "STATION",
				},
				causes: null,
			},
		],
	},
	{
		cancelled: false,
		commuterLineid: "",
		departureDate: "2024-11-26",
		runningCurrently: true,
		trainNumber: 273,
		timetableType: "REGULAR",
		trainType: { name: "PYO", trainCategory: { name: "Long-distance" } },
		trainLocations: [{ speed: 140, location: [25.183906, 65.609026] }],
		trainTrackingMessages: [
			{
				timestamp: "2024-11-26T11:37:12.000Z",
				trackSectionCode: "KVU_V422_KVU",
				nextTrackSectionCode: null,
				previousTrackSectionCode: "KVU_PB472",
				type: "RELEASE",
				station: {
					passengerTraffic: false,
					countryCode: "FI",
					location: [25.206795, 66.16981],
					name: "Koivu",
					shortCode: "KVU",
					uicCode: 362,
					type: "STATION",
				},
				nextStation: null,
				previousStation: null,
			},
		],
		timeTableRows: [
			{
				type: "DEPARTURE",
				trainStopping: true,
				commercialStop: true,
				commercialTrack: "8",
				cancelled: false,
				scheduledTime: "2024-11-26T21:13:00.000Z",
				actualTime: "2024-11-26T21:13:10.000Z",
				differenceInMinutes: 0,
				liveEstimateTime: null,
				estimateSourceType: null,
				unknownDelay: null,
				station: {
					passengerTraffic: true,
					countryCode: "FI",
					location: [24.941249, 60.172097],
					name: "Helsinki asema",
					shortCode: "HKI",
					uicCode: 1,
					type: "STATION",
				},
				causes: null,
			},
		],
	},
	{
		cancelled: false,
		commuterLineid: "",
		departureDate: "2024-11-26",
		runningCurrently: true,
		trainNumber: 276,
		timetableType: "REGULAR",
		trainType: { name: "PYO", trainCategory: { name: "Long-distance" } },
		trainLocations: [{ speed: 74, location: [25.107131, 60.40751] }],
		trainTrackingMessages: [
			{
				timestamp: "2024-11-26T17:44:45.000Z",
				trackSectionCode: "KLI_V612",
				nextTrackSectionCode: null,
				previousTrackSectionCode: "KLI_V611",
				type: "OCCUPY",
				station: {
					passengerTraffic: true,
					countryCode: "FI",
					location: [23.836254, 67.348706],
					name: "Kolari",
					shortCode: "KLI",
					uicCode: 358,
					type: "STATION",
				},
				nextStation: {
					passengerTraffic: false,
					countryCode: "FI",
					location: [23.867383, 67.159514],
					name: "Sieppijärvi",
					shortCode: "SPJ",
					uicCode: 796,
					type: "STATION",
				},
				previousStation: null,
			},
		],
		timeTableRows: [
			{
				type: "DEPARTURE",
				trainStopping: true,
				commercialStop: true,
				commercialTrack: "1",
				cancelled: false,
				scheduledTime: "2024-11-26T17:42:00.000Z",
				actualTime: "2024-11-26T17:42:38.000Z",
				differenceInMinutes: 1,
				liveEstimateTime: null,
				estimateSourceType: null,
				unknownDelay: null,
				station: {
					passengerTraffic: true,
					countryCode: "FI",
					location: [23.836254, 67.348706],
					name: "Kolari",
					shortCode: "KLI",
					uicCode: 358,
					type: "STATION",
				},
				causes: null,
			},
		],
	},
	{
		cancelled: false,
		commuterLineid: "",
		departureDate: "2024-11-27",
		runningCurrently: true,
		trainNumber: 1,
		timetableType: "REGULAR",
		trainType: { name: "IC", trainCategory: { name: "Long-distance" } },
		trainLocations: [{ speed: 82, location: [28.835813, 61.224149] }],
		trainTrackingMessages: [
			{
				timestamp: "2024-11-27T04:49:00.000Z",
				trackSectionCode: "009a",
				nextTrackSectionCode: null,
				previousTrackSectionCode: null,
				type: "OCCUPY",
				station: {
					passengerTraffic: true,
					countryCode: "FI",
					location: [24.941249, 60.172097],
					name: "Helsinki asema",
					shortCode: "HKI",
					uicCode: 1,
					type: "STATION",
				},
				nextStation: {
					passengerTraffic: true,
					countryCode: "FI",
					location: [24.933521, 60.198689],
					name: "Pasila asema",
					shortCode: "PSL",
					uicCode: 10,
					type: "STATION",
				},
				previousStation: null,
			},
		],
		timeTableRows: [
			{
				type: "DEPARTURE",
				trainStopping: true,
				commercialStop: true,
				commercialTrack: "9",
				cancelled: false,
				scheduledTime: "2024-11-27T04:54:00.000Z",
				actualTime: "2024-11-27T04:55:11.000Z",
				differenceInMinutes: 1,
				liveEstimateTime: null,
				estimateSourceType: null,
				unknownDelay: null,
				station: {
					passengerTraffic: true,
					countryCode: "FI",
					location: [24.941249, 60.172097],
					name: "Helsinki asema",
					shortCode: "HKI",
					uicCode: 1,
					type: "STATION",
				},
				causes: null,
			},
		],
	},
	{
		cancelled: false,
		commuterLineid: "",
		departureDate: "2024-11-27",
		runningCurrently: true,
		trainNumber: 4,
		timetableType: "REGULAR",
		trainType: { name: "IC", trainCategory: { name: "Long-distance" } },
		trainLocations: [{ speed: 136, location: [25.705713, 60.970657] }],
		trainTrackingMessages: [
			{
				timestamp: "2024-11-27T03:45:16.000Z",
				trackSectionCode: "9013",
				nextTrackSectionCode: null,
				previousTrackSectionCode: null,
				type: "OCCUPY",
				station: {
					passengerTraffic: true,
					countryCode: "FI",
					location: [29.777033, 62.599536],
					name: "Joensuu asema",
					shortCode: "JNS",
					uicCode: 460,
					type: "STATION",
				},
				nextStation: {
					passengerTraffic: false,
					countryCode: "FI",
					location: [29.771729, 62.593453],
					name: "Joensuu Peltola",
					shortCode: "PLT",
					uicCode: 1070,
					type: "STATION",
				},
				previousStation: null,
			},
		],
		timeTableRows: [
			{
				type: "DEPARTURE",
				trainStopping: true,
				commercialStop: true,
				commercialTrack: "1",
				cancelled: false,
				scheduledTime: "2024-11-27T04:00:00.000Z",
				actualTime: "2024-11-27T04:01:19.000Z",
				differenceInMinutes: 1,
				liveEstimateTime: null,
				estimateSourceType: null,
				unknownDelay: null,
				station: {
					passengerTraffic: true,
					countryCode: "FI",
					location: [29.777033, 62.599536],
					name: "Joensuu asema",
					shortCode: "JNS",
					uicCode: 460,
					type: "STATION",
				},
				causes: null,
			},
		],
	},
	{
		cancelled: false,
		commuterLineid: "",
		departureDate: "2024-11-27",
		runningCurrently: true,
		trainNumber: 6,
		timetableType: "REGULAR",
		trainType: { name: "IC", trainCategory: { name: "Long-distance" } },
		trainLocations: [{ speed: 138, location: [29.901863, 61.996462] }],
		trainTrackingMessages: [
			{
				timestamp: "2024-11-27T06:37:42.000Z",
				trackSectionCode: "9013",
				nextTrackSectionCode: null,
				previousTrackSectionCode: null,
				type: "OCCUPY",
				station: {
					passengerTraffic: true,
					countryCode: "FI",
					location: [29.777033, 62.599536],
					name: "Joensuu asema",
					shortCode: "JNS",
					uicCode: 460,
					type: "STATION",
				},
				nextStation: {
					passengerTraffic: false,
					countryCode: "FI",
					location: [29.771729, 62.593453],
					name: "Joensuu Peltola",
					shortCode: "PLT",
					uicCode: 1070,
					type: "STATION",
				},
				previousStation: null,
			},
		],
		timeTableRows: [
			{
				type: "DEPARTURE",
				trainStopping: true,
				commercialStop: true,
				commercialTrack: "1",
				cancelled: false,
				scheduledTime: "2024-11-27T07:00:00.000Z",
				actualTime: "2024-11-27T07:01:41.000Z",
				differenceInMinutes: 2,
				liveEstimateTime: null,
				estimateSourceType: null,
				unknownDelay: null,
				station: {
					passengerTraffic: true,
					countryCode: "FI",
					location: [29.777033, 62.599536],
					name: "Joensuu asema",
					shortCode: "JNS",
					uicCode: 460,
					type: "STATION",
				},
				causes: null,
			},
		],
	},
	{
		cancelled: false,
		commuterLineid: "",
		departureDate: "2024-11-27",
		runningCurrently: true,
		trainNumber: 20,
		timetableType: "REGULAR",
		trainType: { name: "IC", trainCategory: { name: "Long-distance" } },
		trainLocations: [{ speed: 33, location: [23.773428, 61.501021] }],
		trainTrackingMessages: [
			{
				timestamp: "2024-11-27T02:55:02.000Z",
				trackSectionCode: "001",
				nextTrackSectionCode: null,
				previousTrackSectionCode: null,
				type: "OCCUPY",
				station: {
					passengerTraffic: true,
					countryCode: "FI",
					location: [25.486121, 65.012409],
					name: "Oulu asema",
					shortCode: "OL",
					uicCode: 370,
					type: "STATION",
				},
				nextStation: null,
				previousStation: null,
			},
		],
		timeTableRows: [
			{
				type: "DEPARTURE",
				trainStopping: true,
				commercialStop: true,
				commercialTrack: "1",
				cancelled: false,
				scheduledTime: "2024-11-27T03:21:00.000Z",
				actualTime: "2024-11-27T03:22:00.000Z",
				differenceInMinutes: 1,
				liveEstimateTime: "2024-11-27T03:21:00.000Z",
				estimateSourceType: "LIIKE_AUTOMATIC",
				unknownDelay: null,
				station: {
					passengerTraffic: true,
					countryCode: "FI",
					location: [25.486121, 65.012409],
					name: "Oulu asema",
					shortCode: "OL",
					uicCode: 370,
					type: "STATION",
				},
				causes: null,
			},
		],
	},
	{
		cancelled: false,
		commuterLineid: "",
		departureDate: "2024-11-27",
		runningCurrently: true,
		trainNumber: 21,
		timetableType: "REGULAR",
		trainType: { name: "IC", trainCategory: { name: "Long-distance" } },
		trainLocations: [{ speed: 0, location: [23.034609, 63.100496] }],
		trainTrackingMessages: [
			{
				timestamp: "2024-11-27T04:18:00.000Z",
				trackSectionCode: "009a",
				nextTrackSectionCode: null,
				previousTrackSectionCode: null,
				type: "OCCUPY",
				station: {
					passengerTraffic: true,
					countryCode: "FI",
					location: [24.941249, 60.172097],
					name: "Helsinki asema",
					shortCode: "HKI",
					uicCode: 1,
					type: "STATION",
				},
				nextStation: {
					passengerTraffic: true,
					countryCode: "FI",
					location: [24.933521, 60.198689],
					name: "Pasila asema",
					shortCode: "PSL",
					uicCode: 10,
					type: "STATION",
				},
				previousStation: null,
			},
		],
		timeTableRows: [
			{
				type: "DEPARTURE",
				trainStopping: true,
				commercialStop: true,
				commercialTrack: "9",
				cancelled: false,
				scheduledTime: "2024-11-27T04:23:00.000Z",
				actualTime: "2024-11-27T04:23:34.000Z",
				differenceInMinutes: 1,
				liveEstimateTime: null,
				estimateSourceType: null,
				unknownDelay: null,
				station: {
					passengerTraffic: true,
					countryCode: "FI",
					location: [24.941249, 60.172097],
					name: "Helsinki asema",
					shortCode: "HKI",
					uicCode: 1,
					type: "STATION",
				},
				causes: null,
			},
		],
	},
	{
		cancelled: false,
		commuterLineid: "",
		departureDate: "2024-11-27",
		runningCurrently: true,
		trainNumber: 22,
		timetableType: "REGULAR",
		trainType: { name: "IC", trainCategory: { name: "Long-distance" } },
		trainLocations: [{ speed: 161, location: [22.910721, 63.635456] }],
		trainTrackingMessages: [
			{
				timestamp: "2024-11-27T03:16:46.000Z",
				trackSectionCode: "ROI_V605",
				nextTrackSectionCode: null,
				previousTrackSectionCode: "ROI_V603",
				type: "OCCUPY",
				station: {
					passengerTraffic: true,
					countryCode: "FI",
					location: [25.705329, 66.497675],
					name: "Rovaniemi",
					shortCode: "ROI",
					uicCode: 364,
					type: "STATION",
				},
				nextStation: {
					passengerTraffic: true,
					countryCode: "FI",
					location: [25.37511, 66.370875],
					name: "Muurola",
					shortCode: "MUL",
					uicCode: 363,
					type: "STATION",
				},
				previousStation: null,
			},
		],
		timeTableRows: [
			{
				type: "DEPARTURE",
				trainStopping: true,
				commercialStop: true,
				commercialTrack: "1",
				cancelled: false,
				scheduledTime: "2024-11-27T03:15:00.000Z",
				actualTime: "2024-11-27T03:15:39.000Z",
				differenceInMinutes: 1,
				liveEstimateTime: null,
				estimateSourceType: null,
				unknownDelay: null,
				station: {
					passengerTraffic: true,
					countryCode: "FI",
					location: [25.705329, 66.497675],
					name: "Rovaniemi",
					shortCode: "ROI",
					uicCode: 364,
					type: "STATION",
				},
				causes: null,
			},
		],
	},
	{
		cancelled: false,
		commuterLineid: "",
		departureDate: "2024-11-27",
		runningCurrently: true,
		trainNumber: 23,
		timetableType: "REGULAR",
		trainType: { name: "IC", trainCategory: { name: "Long-distance" } },
		trainLocations: [{ speed: 150, location: [24.021361, 61.121088] }],
		trainTrackingMessages: [
			{
				timestamp: "2024-11-27T06:19:00.000Z",
				trackSectionCode: "010a",
				nextTrackSectionCode: null,
				previousTrackSectionCode: null,
				type: "OCCUPY",
				station: {
					passengerTraffic: true,
					countryCode: "FI",
					location: [24.941249, 60.172097],
					name: "Helsinki asema",
					shortCode: "HKI",
					uicCode: 1,
					type: "STATION",
				},
				nextStation: {
					passengerTraffic: true,
					countryCode: "FI",
					location: [24.933521, 60.198689],
					name: "Pasila asema",
					shortCode: "PSL",
					uicCode: 10,
					type: "STATION",
				},
				previousStation: null,
			},
		],
		timeTableRows: [
			{
				type: "DEPARTURE",
				trainStopping: true,
				commercialStop: true,
				commercialTrack: "10",
				cancelled: false,
				scheduledTime: "2024-11-27T06:24:00.000Z",
				actualTime: "2024-11-27T06:25:25.000Z",
				differenceInMinutes: 1,
				liveEstimateTime: null,
				estimateSourceType: null,
				unknownDelay: null,
				station: {
					passengerTraffic: true,
					countryCode: "FI",
					location: [24.941249, 60.172097],
					name: "Helsinki asema",
					shortCode: "HKI",
					uicCode: 1,
					type: "STATION",
				},
				causes: null,
			},
		],
	},
];
