export const majorStations = {
  // A
  AIN: "Ainola",
  ALV: "Alavus",
  AVP: "Aviapolis",

  // D
  DRA: "Dragsvik",

  // E
  EPZ: "Eläinpuisto-Zoo",
  ENO: "Eno",
  EPO: "Espoo",

  // H
  HPJ: "Haapajärvi",
  HPK: "Haapamäki",
  HPA: "Haaparanta",
  HAA: "Haarajoki",
  HSI: "Haksi",
  HKS: "Hankasalmi",
  HNK: "Hanko asema",
  HKP: "Hanko-Pohjoinen",
  HVA: "Harjavalta",
  HNV: "Heinävesi",
  HKI: "Helsinki asema",
  HNN: "Henna",
  HR: "Herrala",
  HKH: "Hiekkaharju",
  HK: "Hikiä",
  HLS: "Hillosensalmi",
  HH: "Hinthaara",
  HP: "Humppila",
  HPL: "Huopalahti",
  HY: "Hyvinkää asema",
  HL: "Hämeenlinna",
  HM: "Härmä",
  HÖL: "Höljäkkä",

  // I
  ILM: "Iisalmi",
  ITA: "Iittala",
  ILA: "Ilmala asema",
  IMR: "Imatra asema",
  IKR: "Inkeroinen",
  IKO: "Inkoo",
  IKY: "Isokyrö",

  // J
  JNS: "Joensuu asema",
  JK: "Jokela",
  JRS: "Jorvas",
  JTS: "Joutseno",
  JJ: "Juupajoki",
  JY: "Jyväskylä",
  JÄS: "Jämsä",
  JR: "Järvelä",
  JP: "Järvenpää asema",

  // K
  KAJ: "Kajaani",
  KAN: "Kannelmäki",
  KNS: "Kannus",
  KR: "Karjaa",
  KRU: "Karkku",
  KHA: "Kauhava",
  KLH: "Kauklahti asema",
  KNI: "Kauniainen",
  KA: "Kausala",
  KEM: "Kemi asema",
  KJÄ: "Kemijärvi",
  KML: "Kempele",
  KEA: "Kera",
  KE: "Kerava asema",
  KIÄ: "Kerimäki",
  KTI: "Kesälahti",
  KEU: "Keuruu",
  KIA: "Kiiala",
  KIL: "Kilo",
  KKN: "Kirkkonummi",
  KIT: "Kitee",
  KRV: "Kiuruvesi",
  KTÖ: "Kivistö",
  KOH: "Kohtavaara",
  KVH: "Koivuhovi",
  KVY: "Koivukylä",
  KKI: "Kokemäki",
  KOK: "Kokkola",
  KLI: "Kolari",
  KLO: "Kolho",
  KON: "Kontiomäki",
  KRA: "Koria",
  KRS: "Korso",
  KTA: "Kotka asema",
  KTS: "Kotkan satama",
  KV: "Kouvola asema",
  KUO: "Kuopio asema",
  KUT: "Kupittaa",
  KYN: "Kylänlahti",
  KY: "Kymi",
  KLN: "Kyminlinna",
  KÄP: "Käpylä",

  // L
  LH: "Lahti",
  LAI: "Laihia",
  LNA: "Lapinlahti",
  LR: "Lappeenranta",
  LAA: "Lappila",
  LPO: "Lappohja",
  LPA: "Lapua",
  LNÄ: "Leinelä",
  LPÄ: "Lempäälä",
  LEN: "Lentoasema",
  LPV: "Leppävaara",
  LIS: "Lieksa",
  LVT: "Lievestuore",
  LM: "Loimaa",
  LOH: "Louhela",
  LUS: "Lusto",

  // M
  ML: "Malmi",
  MLO: "Malminkartano",
  MRL: "Martinlaakso",
  MAS: "Masala",
  MI: "Mikkeli",
  MIS: "Misi",
  MLA: "Mommila",
  MVA: "Moskova_(Leningradski)",
  MH: "Muhos",
  MUL: "Muurola",
  MKI: "Myllykoski",
  MY: "Myllymäki",
  MYR: "Myyrmäki",
  MÄK: "Mäkkylä",
  MLÄ: "Mäntsälä",
  MR: "Mäntyharju",

  // N
  NSL: "Nastola",
  NLÄ: "Nikkilä",
  NVL: "Nivala",
  NOA: "Nokia",
  NRM: "Nurmes",

  // O
  OI: "Oitti",
  OV: "Orivesi",
  OVK: "Orivesi keskusta",
  OU: "Oulainen",
  OL: "Oulu asema",
  OLK: "Oulunkylä",

  // P
  PTI: "Paimenportti",
  PTO: "Paltamo",
  PAR: "Parikkala",
  PKO: "Parkano",
  PRL: "Parola",
  PSL: "Pasila asema",
  PAU: "Pasila autojuna-asema",
  PEL: "Pello",
  PVI: "Petäjävesi",
  PM: "Pieksämäki asema",
  PTR: "Pietari_(Finljandski)",
  PTL: "Pietari_(Ladozhski)",
  PH: "Pihlajavesi",
  PJM: "Pitäjänmäki",
  POH: "Pohjois-Haaga",
  PRI: "Pori",
  PRV: "Porvoo",
  PLA: "Puistola",
  PMK: "Pukinmäki",
  PUN: "Punkaharju",
  PUR: "Purola",
  PHÄ: "Pyhäsalmi",
  PNÄ: "Pännäinen",
  PKY: "Pääskylahti",

  // R
  RKL: "Rekola",
  REE: "Retretti",
  RI: "Riihimäki asema",
  ROI: "Rovaniemi",
  RNN: "Runni",
  RKI: "Ruukki",
  RY: "Ryttylä",

  // S
  SLO: "Salo",
  STA: "Santala",
  SAU: "Saunakallio",
  SAV: "Savio",
  SL: "Savonlinna asema",
  SK: "Seinäjoki asema",
  SIJ: "Siilinjärvi asema",
  SPL: "Simpele",
  STI: "Siuntio",
  SGY: "Skogby",
  SKV: "Sukeva",
  SNJ: "Suonenjoki",

  // T
  TMS: "Tammisaari",
  TPE: "Tampere asema",
  TNA: "Tapanila",
  TSL: "Tavastila",
  TK: "Tervajoki",
  TRV: "Tervola",
  TSO: "Tesoma",
  TKL: "Tikkurila asema",
  TL: "Toijala",
  TOL: "Tolsa",
  TOR: "Tornio asema",
  TRI: "Tornio-Itäinen",
  TRL: "Tuomarila",
  TU: "Turenki",
  TKU: "Turku asema",
  TUS: "Turku satama",
  TUU: "Tuuri",
  TVE: "Tver",

  // U
  UIM: "Uimaharju",
  UTJ: "Utajärvi",
  UKÄ: "Uusikylä",

  // V
  VAA: "Vaala",
  VS: "Vaasa",
  VNA: "Vainikkala asema",
  VMO: "Valimo",
  VMA: "Vammala",
  VKS: "Vantaankoski",
  VAR: "Varkaus",
  VEH: "Vehkala",
  VTI: "Vihanti",
  VIH: "Vihtari",
  VIA: "Viiala",
  VNJ: "Viinijärvi",
  VYB: "Viipuri",
  VLH: "Villähde",
  VLP: "Vilppula",
  VSL: "Vuonislahti",

  // Y
  YST: "Ylistaro",
  YTR: "Ylitornio",
  YV: "Ylivieska",

  // Ä
  ÄHT: "Ähtäri",
} as const;

export type StationCode = keyof typeof majorStations;

export const isValidStationCode = (code: string): code is StationCode => {
  return code in majorStations;
};
