/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as MapRouteImport } from './app/map'
import { Route as ApiTrainsRouteImport } from './app/api/trains'
import { Route as LiveTrainsIdRouteImport } from './app/live-trains/$id'
import { Route as StationMessagesIdRouteImport } from './app/station-messages/$id'
import { Route as StationsIdRouteImport } from './app/stations/$id'
import { Route as TrainByDateIdRouteImport } from './app/train-by-date/$id'
import { Route as TrainsIdRouteImport } from './app/trains/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrainsRoute = ApiTrainsRouteImport.update({
  id: '/api/trains',
  path: '/api/trains',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveTrainsIdRoute = LiveTrainsIdRouteImport.update({
  id: '/live-trains/$id',
  path: '/live-trains/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StationMessagesIdRoute = StationMessagesIdRouteImport.update({
  id: '/station-messages/$id',
  path: '/station-messages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsIdRoute = StationsIdRouteImport.update({
  id: '/stations/$id',
  path: '/stations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainByDateIdRoute = TrainByDateIdRouteImport.update({
  id: '/train-by-date/$id',
  path: '/train-by-date/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainsIdRoute = TrainsIdRouteImport.update({
  id: '/trains/$id',
  path: '/trains/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/api/trains': typeof ApiTrainsRoute
  '/live-trains/$id': typeof LiveTrainsIdRoute
  '/station-messages/$id': typeof StationMessagesIdRoute
  '/stations/$id': typeof StationsIdRoute
  '/train-by-date/$id': typeof TrainByDateIdRoute
  '/trains/$id': typeof TrainsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/api/trains': typeof ApiTrainsRoute
  '/live-trains/$id': typeof LiveTrainsIdRoute
  '/station-messages/$id': typeof StationMessagesIdRoute
  '/stations/$id': typeof StationsIdRoute
  '/train-by-date/$id': typeof TrainByDateIdRoute
  '/trains/$id': typeof TrainsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/api/trains': typeof ApiTrainsRoute
  '/live-trains/$id': typeof LiveTrainsIdRoute
  '/station-messages/$id': typeof StationMessagesIdRoute
  '/stations/$id': typeof StationsIdRoute
  '/train-by-date/$id': typeof TrainByDateIdRoute
  '/trains/$id': typeof TrainsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/map'
    | '/api/trains'
    | '/live-trains/$id'
    | '/station-messages/$id'
    | '/stations/$id'
    | '/train-by-date/$id'
    | '/trains/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/map'
    | '/api/trains'
    | '/live-trains/$id'
    | '/station-messages/$id'
    | '/stations/$id'
    | '/train-by-date/$id'
    | '/trains/$id'
  id:
    | '__root__'
    | '/'
    | '/map'
    | '/api/trains'
    | '/live-trains/$id'
    | '/station-messages/$id'
    | '/stations/$id'
    | '/train-by-date/$id'
    | '/trains/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapRoute: typeof MapRoute
  ApiTrainsRoute: typeof ApiTrainsRoute
  LiveTrainsIdRoute: typeof LiveTrainsIdRoute
  StationMessagesIdRoute: typeof StationMessagesIdRoute
  StationsIdRoute: typeof StationsIdRoute
  TrainByDateIdRoute: typeof TrainByDateIdRoute
  TrainsIdRoute: typeof TrainsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trains': {
      id: '/api/trains'
      path: '/api/trains'
      fullPath: '/api/trains'
      preLoaderRoute: typeof ApiTrainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-trains/$id': {
      id: '/live-trains/$id'
      path: '/live-trains/$id'
      fullPath: '/live-trains/$id'
      preLoaderRoute: typeof LiveTrainsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station-messages/$id': {
      id: '/station-messages/$id'
      path: '/station-messages/$id'
      fullPath: '/station-messages/$id'
      preLoaderRoute: typeof StationMessagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations/$id': {
      id: '/stations/$id'
      path: '/stations/$id'
      fullPath: '/stations/$id'
      preLoaderRoute: typeof StationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train-by-date/$id': {
      id: '/train-by-date/$id'
      path: '/train-by-date/$id'
      fullPath: '/train-by-date/$id'
      preLoaderRoute: typeof TrainByDateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trains/$id': {
      id: '/trains/$id'
      path: '/trains/$id'
      fullPath: '/trains/$id'
      preLoaderRoute: typeof TrainsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapRoute: MapRoute,
  ApiTrainsRoute: ApiTrainsRoute,
  LiveTrainsIdRoute: LiveTrainsIdRoute,
  StationMessagesIdRoute: StationMessagesIdRoute,
  StationsIdRoute: StationsIdRoute,
  TrainByDateIdRoute: TrainByDateIdRoute,
  TrainsIdRoute: TrainsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
